#!/bin/bash


echo "Hey choose an option : "
echo "a = To see the current date :"
echo "b = To list the script :"
echo "c =  current location :"
read choice 

case $choice in 
	a)
		echo "printing todays date :)"
		date
		;;
	b)ls;;
	c)pwd;;
	*)echo "please provide a valid vlaue"

esac

